# https://docs.travis-ci.com/
language: python

sudo: false

python:
  - "3.5"
  - "3.6"

cache: pip

services:
  - mongodb
  - redis-server

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
  - pip --version
  - pip freeze # show packages version

script:
  - pytest -v
  - py.test -v --cov=quantbube --cov-report html

after_success:
 # run codecov report
  - codecov -e $TRAVIS_PYTHON_VERSION

