# https://docs.travis-ci.com/
language: python

sudo: no

python:
  - "3.5"
  - "3.6"

cache: pip

addons:
  packages:
      - gcc
      - g++
      - cmake
      - wget

services:
  - mongodb
  - redis-server

before_install:
  # install bcolz packages
  - gcc -v && g++ -v && cmake --version
  - git clone git://github.com/Blosc/c-blosc.git ./blosc -b master
  - cd ./blosc && mkdir build && cd build
  - cmake ..
  - cmake --build .
  - sudo cmake --build . --target install
  - cd ../..  # back to repository directory

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
  - pip --version
  - pip freeze # show packages version


script:
  - pytest -v
  - py.test -v --cov=quantbube --cov-report xml

after_success:
 # run codecov report
  - codecov -e $TRAVIS_PYTHON_VERSION

